# Generated by Django 6.0.3 on 2026-03-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='rotation',
            field=models.IntegerField(default=0, help_text='Rotation angle in degrees (0, 90, 180, 270)'),
        ),
    ]
