# Generated by Django 6.0.3 on 2026-03-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='autoplay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='loop_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='title_overlay',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
