# Generated by Django 6.0.3 on 2026-03-08 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_playlist_autoplay_playlist_description_and_more'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceassignment',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='playlists.playlist'),
        ),
    ]
